/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Caption {
  'tiktok' : string,
  'instagram' : string,
  'facebook' : string,
}
export type ExternalBlob = Uint8Array;
export interface Itinerary {
  'id' : string,
  'cta' : string,
  'days' : Array<string>,
  'hook' : string,
}
export type Platform = { 'tiktok' : null } |
  { 'instagram' : null } |
  { 'facebook' : null };
export interface ScheduledPost {
  'scheduledTime' : Time,
  'platforms' : Array<Platform>,
  'workspace' : Workspace,
  'captions' : Caption,
  'videoId' : string,
}
export type Time = bigint;
export interface Video {
  'id' : string,
  'thumbnail' : [] | [ExternalBlob],
  'file' : ExternalBlob,
  'caption' : string,
  'workspace' : Workspace,
}
export type Workspace = { 'travel' : null } |
  { 'aiLearning' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getAllItineraries' : ActorMethod<[], Array<Itinerary>>,
  'getAllScheduledPosts' : ActorMethod<[], Array<ScheduledPost>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getScheduledPosts' : ActorMethod<[Workspace], Array<ScheduledPost>>,
  'getVideoWorkspace' : ActorMethod<[string], Workspace>,
  'getVideosByWorkspace' : ActorMethod<[Workspace], Array<Video>>,
  'saveItinerary' : ActorMethod<
    [string, string, Array<string>, string],
    undefined
  >,
  'schedulePost' : ActorMethod<
    [string, Workspace, Array<Platform>, Caption, Time],
    undefined
  >,
  'uploadVideo' : ActorMethod<
    [Workspace, string, ExternalBlob, string, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];