/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Itinerary = IDL.Record({
  'id' : IDL.Text,
  'cta' : IDL.Text,
  'days' : IDL.Vec(IDL.Text),
  'hook' : IDL.Text,
});
export const Time = IDL.Int;
export const Platform = IDL.Variant({
  'tiktok' : IDL.Null,
  'instagram' : IDL.Null,
  'facebook' : IDL.Null,
});
export const Workspace = IDL.Variant({
  'travel' : IDL.Null,
  'aiLearning' : IDL.Null,
});
export const Caption = IDL.Record({
  'tiktok' : IDL.Text,
  'instagram' : IDL.Text,
  'facebook' : IDL.Text,
});
export const ScheduledPost = IDL.Record({
  'scheduledTime' : Time,
  'platforms' : IDL.Vec(Platform),
  'workspace' : Workspace,
  'captions' : Caption,
  'videoId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Video = IDL.Record({
  'id' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'file' : ExternalBlob,
  'caption' : IDL.Text,
  'workspace' : Workspace,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAllItineraries' : IDL.Func([], [IDL.Vec(Itinerary)], ['query']),
  'getAllScheduledPosts' : IDL.Func([], [IDL.Vec(ScheduledPost)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getScheduledPosts' : IDL.Func(
      [Workspace],
      [IDL.Vec(ScheduledPost)],
      ['query'],
    ),
  'getVideoWorkspace' : IDL.Func([IDL.Text], [Workspace], ['query']),
  'getVideosByWorkspace' : IDL.Func([Workspace], [IDL.Vec(Video)], ['query']),
  'saveItinerary' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'schedulePost' : IDL.Func(
      [IDL.Text, Workspace, IDL.Vec(Platform), Caption, Time],
      [],
      [],
    ),
  'uploadVideo' : IDL.Func(
      [Workspace, IDL.Text, ExternalBlob, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Itinerary = IDL.Record({
    'id' : IDL.Text,
    'cta' : IDL.Text,
    'days' : IDL.Vec(IDL.Text),
    'hook' : IDL.Text,
  });
  const Time = IDL.Int;
  const Platform = IDL.Variant({
    'tiktok' : IDL.Null,
    'instagram' : IDL.Null,
    'facebook' : IDL.Null,
  });
  const Workspace = IDL.Variant({
    'travel' : IDL.Null,
    'aiLearning' : IDL.Null,
  });
  const Caption = IDL.Record({
    'tiktok' : IDL.Text,
    'instagram' : IDL.Text,
    'facebook' : IDL.Text,
  });
  const ScheduledPost = IDL.Record({
    'scheduledTime' : Time,
    'platforms' : IDL.Vec(Platform),
    'workspace' : Workspace,
    'captions' : Caption,
    'videoId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Video = IDL.Record({
    'id' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'file' : ExternalBlob,
    'caption' : IDL.Text,
    'workspace' : Workspace,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAllItineraries' : IDL.Func([], [IDL.Vec(Itinerary)], ['query']),
    'getAllScheduledPosts' : IDL.Func([], [IDL.Vec(ScheduledPost)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getScheduledPosts' : IDL.Func(
        [Workspace],
        [IDL.Vec(ScheduledPost)],
        ['query'],
      ),
    'getVideoWorkspace' : IDL.Func([IDL.Text], [Workspace], ['query']),
    'getVideosByWorkspace' : IDL.Func([Workspace], [IDL.Vec(Video)], ['query']),
    'saveItinerary' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'schedulePost' : IDL.Func(
        [IDL.Text, Workspace, IDL.Vec(Platform), Caption, Time],
        [],
        [],
      ),
    'uploadVideo' : IDL.Func(
        [Workspace, IDL.Text, ExternalBlob, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };